/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-02 10:34:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div id=\"controls\">\r\n");
      out.write("            <aside id=\"leftmenu\">\r\n");
      out.write("                <div id=\"leftmenu-wrap\">\r\n");
      out.write("                    <div class=\"panel-group slim-scroll\" role=\"tablist\">\r\n");
      out.write("                        <div class=\"panel panel-default\">\r\n");
      out.write("                            <div id=\"leftmenuNav\" class=\"panel-collapse collapse in\" role=\"tabpanel\">\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    <!--  NAVIGATION Content -->\r\n");
      out.write("                                    <ul id=\"navigation\">\r\n");
      out.write("                                        <li class=\"active open\">\r\n");
      out.write("                                            <a href=\"index.html\">\r\n");
      out.write("                                                <i class=\"fa fa-dashboard\"></i>\r\n");
      out.write("                                                <span>Dashboard</span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                                <i class=\"fa fa-list\"></i>\r\n");
      out.write("                                                <span>Manage Package</span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"addPackage.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>Add Package</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"viewPackage.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>View Package</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                                <i class=\"fa fa-leaf\"></i>\r\n");
      out.write("                                                <span>Manage Complain</span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"viewComplain.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>View Complain</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                                <i class=\"fa fa-delicious\"></i>\r\n");
      out.write("                                                <span>Manage Feedback</span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"viewFeedback.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>View Feedback\r\n");
      out.write("                                                    </a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                                <i class=\"fa fa-table\"></i>\r\n");
      out.write("                                                <span>Manage Case</span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"addCase.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>Add Case</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"viewCase.html\">\r\n");
      out.write("                                                        <i class=\"fa fa-angle-right\"></i>View Case</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        \r\n");
      out.write("                                                              </ul>\r\n");
      out.write("                                    <!--/ NAVIGATION Content -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("            <aside id=\"rightmenu\">\r\n");
      out.write("                <div role=\"tabpanel\">\r\n");
      out.write("                    <!-- Nav tabs -->\r\n");
      out.write("                    <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("                        <li role=\"presentation\" class=\"active\">\r\n");
      out.write("                            <a href=\"#chat\" aria-controls=\"chat\" role=\"tab\" data-toggle=\"tab\">Chat</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li role=\"presentation\">\r\n");
      out.write("                            <a href=\"#todo\" aria-controls=\"todo\" role=\"tab\" data-toggle=\"tab\">Todo</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li role=\"presentation\">\r\n");
      out.write("                            <a href=\"#settings\" aria-controls=\"settings\" role=\"tab\" data-toggle=\"tab\">Settings</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- Tab panes -->\r\n");
      out.write("                    <div class=\"tab-content\">\r\n");
      out.write("                        <div role=\"tabpanel\" class=\"tab-pane active\" id=\"chat\">\r\n");
      out.write("                            <div class=\"search\">\r\n");
      out.write("                                <div class=\"form-group is-empty\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control underline-input\" placeholder=\"Search...\">\r\n");
      out.write("                                    <span class=\"material-input\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h6>Recent</h6>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar1.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"name\">Claire Sassu</span>\r\n");
      out.write("                                            <span class=\"message\"> If you are going to use a passage of Lorem Ipsum</span>\r\n");
      out.write("                                            <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar8.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name\">Maggie jackson</span>\r\n");
      out.write("                                                <span class=\"message\">All the Lorem Ipsum generators on the Internet</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar3.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name\">Joel King</span>\r\n");
      out.write("                                                <span class=\"message\">The standard chunk of Lorem Ipsum used</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar6.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name\">Isabella</span>\r\n");
      out.write("                                                <span class=\"message\">There are many variations of passages of Lorem</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\" tabindex=\"0\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar5.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name\">Alexander</span>\r\n");
      out.write("                                                <span class=\"message\">Contrary to popular belief, Lorem Ipsum</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h6>Contacts</h6>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"offline\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar5.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name mt-5\">Matthew</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"offline\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar4.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name mt-5\">Aaliyah</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"offline\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar8.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name mt-5\">Arianna</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"online\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar9.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name mt-5\">Scarlett</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"offline\">\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <a class=\"pull-left thumb thumb-sm\" role=\"button\">\r\n");
      out.write("                                            <img class=\"media-object \" src=\"assets/images/xs/avatar10.jpg\" alt=\"\"> </a>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <div class=\"media-body\">\r\n");
      out.write("                                                <span class=\"name mt-5\">David</span>\r\n");
      out.write("                                                <span class=\"badge badge-outline status\"></span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div role=\"tabpanel\" class=\"tab-pane\" id=\"todo\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" value=\"\" placeholder=\"Create new task...\" class=\"form-control\" />\r\n");
      out.write("                                <span class=\"fa fa-plus\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h6>Today</h6>\r\n");
      out.write("                            <ul class=\"todo-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> Initialize the project</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> Create the main structure</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> Create the main structure</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h6>Tomorrow</h6>\r\n");
      out.write("                            <ul class=\"todo-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> Initialize the project</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> Create the main structure</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"checkbox\">\r\n");
      out.write("                                        <label>\r\n");
      out.write("                                            <input type=\"checkbox\" name=\"optionsCheckboxes\"> displayed in a normal space!</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div role=\"tabpanel\" class=\"tab-pane\" id=\"settings\">\r\n");
      out.write("                            <h6>Chat Settings</h6>\r\n");
      out.write("                            <ul class=\"settings\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">Show Offline Users</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\" checked=\"\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">Show Fullname</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">History Enable</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\" checked=\"\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">Show Locations</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\" checked=\"\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">Notifications</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-xs-8 control-label\">Show Undread Count</label>\r\n");
      out.write("                                        <div class=\"col-xs-4 control-label text-right\">\r\n");
      out.write("                                            <div class=\"togglebutton\">\r\n");
      out.write("                                                <label>\r\n");
      out.write("                                                    <input type=\"checkbox\">\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("        </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
