/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-11 15:29:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--//================About starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB80\">\r\n");
      out.write("            <div class=\"container marB50\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color green pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"#\">BUS SERVICE</a></h4>\r\n");
      out.write("                                <p>Pick and drop service is provided for the babies so that parents feel safe.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color theme-bg pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"#\">MANY SPORTS</a></h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                Sports activities that help babies for their overall development.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color yellow pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-headphones\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"#\">Interactive Elements</a></h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                Dance,music and many such activities are provided for the babies to grow.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color orange pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-cutlery\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"#\">FOOD</a></h4>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                Hygenic Food will be provided and babies will be served different food everday.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color purple pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-music\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"service.html\">MUSIC LESSON</a></h4>\r\n");
      out.write("                                <p>Babies will be taught playing different instrument and will compete with each other.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"service-color red pad30 marB30\">\r\n");
      out.write("                            <div class=\"service-icon\">\r\n");
      out.write("                                <i class=\"fa fa-language\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service-text text-left\">\r\n");
      out.write("                                <h4 class=\"title\"><a href=\"#\">LANGUAGES</a></h4>\r\n");
      out.write("                                <p>Languages like English and Hindi will be taught by the teachers.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clear\"></div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div id=\"about-us-slider\" class=\"owl-carousel owl-theme slider positionR marB30\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure>\r\n");
      out.write("                                    <img src=\"userResources/images/About-us-1.jpg\" alt=\"\"/>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure>\r\n");
      out.write("                                    <img src=\"userResources/images/About-us-2.jpg\" alt=\"\"/>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure>\r\n");
      out.write("                                    <img src=\"userResources/images/About-us-3.jpg\" alt=\"\"/>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure>\r\n");
      out.write("                                    <img src=\"userResources/images/About-us-4.jpg\" alt=\"\"/>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"about-us marB0\">\r\n");
      out.write("                            <h3 class=\"marB10\">Why Choose Us</h3>\r\n");
      out.write("                            <p class=\"text-left\">Baby Monitoring System is a project in \r\n");
      out.write("                            \twhich user can monitor their babies through the camera or video.\r\n");
      out.write("                            \tThe User can get alert through mail if their baby has fallen somewhere \r\n");
      out.write("                            \tor if it is crying or is angry.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"text-left marB30\">To help parents the product can detect babies who have fallen somewhere , \r\n");
      out.write("                            \tare crying and if they are angry. To automate the identification of child`s \r\n");
      out.write("                            \tstatus from a visual monitoring device. The portal is easy to use and access. \r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================About end==============//-->\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
