/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-12 02:45:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer class=\"main_footer\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"footer-box padT80 padB50\">\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <div class=\"foot-sec marB30\">\r\n");
      out.write("                                <h4 class=\"title colorW marB20\">about us</h4>\r\n");
      out.write("                                <ul class=\"text\">\r\n");
      out.write("                                    <li> \r\n");
      out.write("                                        The Best Feeling a child can have is when there is someone \r\n");
      out.write("                                    \twho can capture the smallest actions of him. \r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li> \r\n");
      out.write("                                        <i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <span>aakashjagwani09@gmail.com</span>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li> \r\n");
      out.write("                                        <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <span>P: 8758 137 760</span>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li> \r\n");
      out.write("                                        <i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                        <span> 241 Maharathi Society Sardarnagar - Ahmedabad Gujarat India 382475 </span>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <div class=\"foot-sec marB30\">\r\n");
      out.write("                                <h4 class=\"title colorW marB20\">Useful Links</h4>\r\n");
      out.write("                                <ul class=\"pad0\">\r\n");
      out.write("                                    <li><a href=\"showResult.html\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby Fallen Service</a></li>\r\n");
      out.write("                                    <li><a href=\"showImage.html\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby Expression Detection</a></li>\r\n");
      out.write("                                    <li><a href=\"addFeedbackUser.html\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby House Feedback Service</a></li>\r\n");
      out.write("                                    <li><a href=\"subscriptionUser.html\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby House Subscription Link</a></li>\r\n");
      out.write("                                    <li><a href=\"about.html\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby House About us</a></li>\r\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i>Baby House Contact us</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <div class=\"foot-sec foot-img-box marB30\">\r\n");
      out.write("                                <h4 class=\"title colorW marB20\">Recent Work</h4>\r\n");
      out.write("                                <ul class=\"pad0\">\r\n");
      out.write("                                    <li><a href=\"#\"><img src=\"userResources/images/Angry-Little-Baby.jpg_detected.jpg\" alt=\"\"/></a></li>\r\n");
      out.write("                                    <li><a href=\"#\"><img src=\"userResources/images/cry.jpg_detected.jpg\" alt=\"\"/></a></li>\r\n");
      out.write("                                    <li><a href=\"#\"><img src=\"userResources/images/sixth.mp4_detected.jpg\" alt=\"\"/></a></li>\r\n");
      out.write("                                    <li><a href=\"#\"><img src=\"userResources/images/ninth.mp4_detected.jpg\" alt=\"\"/></a></li>\r\n");
      out.write("                                    <li><a href=\"#\"><img src=\"userResources/images/Cute-Happy-Baby-Picture.jpg_detected.jpg\" alt=\"\"/></a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <div class=\"foot-sec marB30\">\r\n");
      out.write("                                <h4 class=\"title colorW marB20\">Mailing List</h4>\r\n");
      out.write("                                <p>Sign up for our mailing list to get latest updates and offers.</p>\r\n");
      out.write("                                <div class=\"search_bar marB15\">\r\n");
      out.write("                                    <input type=\"text\" name=\"search\" placeholder=\"Search..\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"default-btn\"><i class=\"fa fa-paper-plane\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>We respect your privacy</p>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    <a href=\"#\" class=\"square-box default-btn\"><span><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></span></a>\r\n");
      out.write("                                    <a href=\"#\" class=\"square-box default-btn\"><span><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></span></a>\r\n");
      out.write("                                    <a href=\"#\" class=\"square-box default-btn\"><span><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></span></a>\r\n");
      out.write("                                    <a href=\"#\" class=\"square-box default-btn\"><span><i class=\"fa fa-instagram\" aria-hidden=\"true\"></i></span></a>\r\n");
      out.write("                                    <a href=\"#\" class=\"square-box default-btn\"><span><i class=\"fa fa-pinterest\" aria-hidden=\"true\"></i></span></a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
