/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-11 09:23:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div class=\"preloader\">\r\n");
      out.write("            <div class=\"thecube\">\r\n");
      out.write("                <div class=\"cube c1\"></div>\r\n");
      out.write("                <div class=\"cube c2\"></div>\r\n");
      out.write("                <div class=\"cube c4\"></div>\r\n");
      out.write("                <div class=\"cube c3\"></div>\r\n");
      out.write("                <h4>Loading</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"top-bar\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>aakashjagwani09@gmail.com</a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>8758137760</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 col-sm-6 col-xs-12 text-right small-left\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <!-- <li><a href=\"logout.html\" ><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>Welcome</a></li>\r\n");
      out.write("                                 -->\r\n");
      out.write("                                 <li><a href=\"spring_logout\" ><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>Logout</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"main-menu\" class=\"wa-main-menu\">\r\n");
      out.write("                <!-- Menu -->\r\n");
      out.write("                <div class=\"wathemes-menu relative\">\r\n");
      out.write("                    <!-- navbar -->\r\n");
      out.write("                    <div class=\"navbar navbar-default theme-bg mar0\" role=\"navigation\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"right-pink-shape\">\r\n");
      out.write("                                        <div class=\"navbar-header\">\r\n");
      out.write("                                            <!-- Button For Responsive toggle -->\r\n");
      out.write("                                            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                                            <span class=\"sr-only\">Toggle navigation</span> \r\n");
      out.write("                                            <span class=\"icon-bar\"></span> \r\n");
      out.write("                                            <span class=\"icon-bar\"></span> \r\n");
      out.write("                                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                                            </button> \r\n");
      out.write("                                            <!-- Logo -->\r\n");
      out.write("                                            <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                                            <img class=\"site_logo\" alt=\"Site Logo\"  src=\"userResources/images/logo.png\" />\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!-- Navbar Collapse -->\r\n");
      out.write("                                        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                                            <!-- nav -->\r\n");
      out.write("                                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                                                <li><a href=\"index.html\">home</a></li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"#\">pages<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                                        <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                                                        <li><a href=\"register.html\">Register</a></li>\r\n");
      out.write("                                                        <li><a href=\"subscriptionUser.html\">Subscription Package</a></li>\r\n");
      out.write("                                                        <li><a href=\"addComplainUser.html\">Add Complaint</a></li>\r\n");
      out.write("                                                        <li><a href=\"addFeedbackUser.html\">Add Feedback</a></li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                 ");

												Integer s=(Integer) session.getAttribute("loginId");
												session.setAttribute("s",s);
											
											   	 
      out.write("\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <a href=\"#\">service<i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                                                    <ul class=\"dropdown-menu\">\t \r\n");
      out.write("                                                        <li><a href=\"showResult.html\">Fall Down Service</a></li>\r\n");
      out.write("                                                        <li><a href=\"showImage.html\">Expression Detection Service</a></li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"contact.html\">contact</a></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!-- navbar-collapse -->\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- col-md-12 -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- row -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- container -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- navbar -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--  Menu -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
