/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-12 03:59:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <!--[if IE]>\r\n");
      out.write("        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("        <meta name=\"keywords\" content=\"HTML5 Template\" />\r\n");
      out.write("        <meta name=\"description\" content=\"Baby House - Kids School, Kinder Garden & Play School Multipurpose HTML5 Template\" />\r\n");
      out.write("        <meta name=\"author\" content=\"itgeeksin.com\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("        <title>Baby House </title>\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("        <!-- Favicon -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"userResources/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("        <link rel=\"icon\" href=\"userResources/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("        <!-- Master Css -->\r\n");
      out.write("        <link href=\"userResources/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("        <!--//================Slider start==============//--> \r\n");
      out.write("        <section id=\"slider-section\">\r\n");
      out.write("            <div id=\"main-slider\" class=\"owl-carousel owl-theme slider positionR\">\r\n");
      out.write("                <div class=\"item positionR\">\r\n");
      out.write("                    <figure class=\"slider-image positionR\">\r\n");
      out.write("                        <img src=\"userResources/images/main-1.jpg\" alt=\"\" class=\"hidden-xs\"/>\r\n");
      out.write("                        <img src=\"userResources/images/main-xs-1.jpg\" alt=\"\" class=\"hidden-sm hidden-lg hidden-md\"/>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"slider-text positionA text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-8 col-sm-8 col-xs-10 col-md-offset-2 col-sm-offset-2 col-xs-offset-1 text-center\">\r\n");
      out.write("                                    <h1>Baby House</h1>\r\n");
      out.write("                                    <h2>Care School for baby</h2>\r\n");
      out.write("                                    <p>The Best Feeling a child can have is when there is someone \r\n");
      out.write("                                    \twho can capture the smallest actions of him. \r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item positionR\">\r\n");
      out.write("                    <figure class=\"slider-image positionR\">\r\n");
      out.write("                        <img src=\"userResources/images/main-2.jpg\" alt=\"\" class=\"hidden-xs\"/>\r\n");
      out.write("                        <img src=\"userResources/images/main-xs-2.jpg\" alt=\"\" class=\"hidden-sm hidden-lg hidden-md\"/>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"slider-text positionA text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-8 col-sm-8 col-xs-10 col-md-offset-2 col-sm-offset-2 col-xs-offset-1 text-center\">\r\n");
      out.write("                                    <h1>Baby House</h1>\r\n");
      out.write("                                    <h2>Care School for baby</h2>\r\n");
      out.write("                                    <p>The Best Feeling a child can have is when there is someone \r\n");
      out.write("                                    \twho can capture the smallest actions of him. \r\n");
      out.write("                                   </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item positionR\">\r\n");
      out.write("                    <figure class=\"slider-image positionR\">\r\n");
      out.write("                        <img src=\"userResources/images/main-3.jpg\" alt=\"\" class=\"hidden-xs\"/>\r\n");
      out.write("                        <img src=\"userResources/images/main-xs-3.jpg\" alt=\"\" class=\"hidden-sm hidden-lg hidden-md\"/>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"slider-text positionA text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-8 col-sm-8 col-xs-10 col-md-offset-2 col-sm-offset-2 col-xs-offset-1 text-center\">\r\n");
      out.write("                                    <h1>Baby House</h1>\r\n");
      out.write("                                    <h2>Care School for baby</h2>\r\n");
      out.write("                                    <p>The Best Feeling a child can have is when there is someone \r\n");
      out.write("                                    \twho can capture the smallest actions of him. \r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Slider end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        \r\n");
      out.write("        ");

												Integer s=(Integer) session.getAttribute("loginId");
												session.setAttribute("s",s);
		
      out.write("\t \r\n");
      out.write("        <!--//================services starts==============//-->\r\n");
      out.write("        <section class=\"padT50 padB20 theme-border-bottom\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12 padB30\">\r\n");
      out.write("                        <div class=\"service-icon\">\r\n");
      out.write("                            <i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <h4>Opening hours</h4>\r\n");
      out.write("                            <p>9.00 am - 5pm</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12 padB30\">\r\n");
      out.write("                        <div class=\"service-icon\">\r\n");
      out.write("                            <i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <h4>Our Email</h4>\r\n");
      out.write("                            <p>aakashjagwani09@gmail.com</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12 padB30\">\r\n");
      out.write("                        <div class=\"service-icon\">\r\n");
      out.write("                            <i class=\"fa fa-bus\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <h4>Bus Timing</h4>\r\n");
      out.write("                            <p>8.00 am</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12 padB30\">\r\n");
      out.write("                        <div class=\"service-icon\">\r\n");
      out.write("                            <i class=\"fa fa-phone\" aria-hidden=\"true\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service-text\">\r\n");
      out.write("                            <h4>Phone Number</h4>\r\n");
      out.write("                            <p>+91 8758137760</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================services end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "aboutUs.jsp", out, false);
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Facilities starts==============//-->\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"special-style theme-overlay\">\r\n");
      out.write("                <!-- <div class=\"facilities-image parallax-style\"></div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"facilities padT80 padB50\">\r\n");
      out.write("                <!--- Theme heading start-->\r\n");
      out.write("                <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                                <h3 class=\"colorW marB10\">Our Facilities</h3>\r\n");
      out.write("                                <span class=\"colorW marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                                <p class=\"colorW marB10\">\r\n");
      out.write("                                The Best Feeling a child can have is when there is someone\r\n");
      out.write("                                who can capture the smallest actions of him. \r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--- Theme heading end-->\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 col-sm-6 col-xs-12 pull-right\">\r\n");
      out.write("                            <div id=\"facilities-slider\" class=\"owl-carousel owl-theme slider positionR marB30\">\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/facilities-1.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/facilities-2.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/facilities-3.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/facilities-4.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                            <div class=\"facilities-details\">\r\n");
      out.write("                                <h3 class=\"colorW text-left marB10\">Facilities our product will provide</h3>\r\n");
      out.write("                                <p class=\"colorW text-left marB30\">\r\n");
      out.write("                                Our product will provide the basic functionality of baby monitoring so that \r\n");
      out.write("                                busy parents can monitor their child while they work so thay wont \r\n");
      out.write("                                have to remain the whole day at home.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"row hidden-sm\">\r\n");
      out.write("                                    <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                        <div class=\"service-color marB30\">\r\n");
      out.write("                                            <div class=\"service-icon\">\r\n");
      out.write("                                                <i class=\"fa fa-futbol-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"service-text text-left\">\r\n");
      out.write("                                                <h4 class=\"title\"><a href=\"#\">MANY SPORTS</a></h4>\r\n");
      out.write("                                                <p>Sports activities that help babies for their overall development.</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                        <div class=\"service-color marB30\">\r\n");
      out.write("                                            <div class=\"service-icon\">\r\n");
      out.write("                                                <i class=\"fa fa-paint-brush\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"service-text text-left\">\r\n");
      out.write("                                                <h4 class=\"title\"><a href=\"#\">Painting</a></h4>\r\n");
      out.write("                                                <p>Painting during the school hours to help your child learn Art.   \r\n");
      out.write("                                                </p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                        <div class=\"service-color marB30\">\r\n");
      out.write("                                            <div class=\"service-icon text-left\">\r\n");
      out.write("                                                <i class=\"fa fa-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"service-text\">\r\n");
      out.write("                                                <h4 class=\"title\"><a href=\"#\">LIBRARY</a></h4>\r\n");
      out.write("                                                <p>There is a Library of New and Good books for childs</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                        <div class=\"service-color marB30\">\r\n");
      out.write("                                            <div class=\"service-icon\">\r\n");
      out.write("                                                <i class=\"fa fa-music\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"service-text text-left\">\r\n");
      out.write("                                                <h4 class=\"title\"><a href=\"#\">MUSIC LESSON</a></h4>\r\n");
      out.write("                                                <p>There are Also music class to help child learn basics of Music.</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"clear\"></div>\r\n");
      out.write("                        <div class=\"hidden-xs hidden-md hidden-lg\">\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                <div class=\"service-color marB30\">\r\n");
      out.write("                                    <div class=\"service-icon\">\r\n");
      out.write("                                        <i class=\"fa fa-futbol-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"service-text text-left\">\r\n");
      out.write("                                        <h4><a href=\"#\">MANY SPORTS</a></h4>\r\n");
      out.write("                         \t\t\t\t\t<p>Sports activities that help babies for their overall development.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                <div class=\"service-color marB30\">\r\n");
      out.write("                                    <div class=\"service-icon\">\r\n");
      out.write("                                        <i class=\"fa fa-paint-brush\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"service-text text-left\">\r\n");
      out.write("                                        <h4><a href=\"#\">Painting</a></h4>\r\n");
      out.write("                          \t\t\t\t\t<p>Painting during the school hours to help your child learn Art.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                <div class=\"service-color marB30\">\r\n");
      out.write("                                    <div class=\"service-icon text-left\">\r\n");
      out.write("                                        <i class=\"fa fa-book\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"service-text\">\r\n");
      out.write("                                        <h4><a href=\"#\">LIBRARY</a></h4>\r\n");
      out.write("                      \t\t                <p>There is a Library of New and Good books for childs</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                                <div class=\"service-color marB30\">\r\n");
      out.write("                                    <div class=\"service-icon\">\r\n");
      out.write("                                        <i class=\"fa fa-music\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"service-text text-left\">\r\n");
      out.write("                                        <h4><a href=\"#\">MUSIC LESSON</a></h4>\r\n");
      out.write("                      \t\t\t            <p>There are Also music class to help child learn basics of Music.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Facilities end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Gallery starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB50\">\r\n");
      out.write("            <!--- Theme heading start-->\r\n");
      out.write("            <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                            <h3 class=\"theme-color marB10\">Our Gallery</h3>\r\n");
      out.write("                            <span class=\" marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            <p class=\" marB10\">\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--- Theme heading end-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-8 col-sm-8 col-xs12\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12 marB30\">\r\n");
      out.write("                                <div class=\"theme-hover\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/Angry-Little-Baby.jpg_detected.jpg\" alt=\"\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-sm-6 col-xs-12 marB30\">\r\n");
      out.write("                                <div class=\"theme-hover\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/cry.jpg_detected.jpg\" alt=\"\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 col-sm-12 col-xs-12 marB30\">\r\n");
      out.write("                                <div class=\"theme-hover\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/sixth.mp4_detected.jpg\" alt=\"\" class=\"hidden-xs\">\r\n");
      out.write("                                      </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4 col-xs12\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12 col-sm-12 col-xs-12 marB30\">\r\n");
      out.write("                                <div class=\"theme-hover\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/Cute-Happy-Baby-Picture.jpg_detected.jpg\" alt=\"\" class=\"hidden-xs\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Gallery end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Our Staff starts==============//-->\r\n");
      out.write("        <section class=\"padT50 padB50 bagG\">\r\n");
      out.write("            <!--- Theme heading start-->\r\n");
      out.write("            <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                            <h3 class=\"theme-color marB10\">Our Staff</h3>\r\n");
      out.write("                            <span class=\" marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            <p class=\" marB10\">\r\n");
      out.write("                            The Best Feeling a child can have is when there is someone \r\n");
      out.write("                            who can capture the smallest actions of him.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--- Theme heading end-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                        <div class=\"theme-hover marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/aakash.jpg\" alt=\"\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                            <div class=\"staff-details text-center padT20\">\r\n");
      out.write("                                <h4><a href=\"staff-detail.html\">Aakash Jagwani</a></h4>\r\n");
      out.write("                                <p class=\"theme-color marB10\">Admin</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                        <div class=\"theme-hover marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/vrinda.jpg\" alt=\"\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                            <div class=\"staff-details text-center padT20\">\r\n");
      out.write("                                <h4><a href=\"staff-detail.html\">Vrinda Hotwani</a></h4>\r\n");
      out.write("                                <p class=\"theme-color marB10\">Admin</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                        <div class=\"theme-hover marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/reena.jpg\" alt=\"\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                            <div class=\"staff-details text-center padT20\">\r\n");
      out.write("                                <h4><a href=\"staff-detail.html\">Reena Chhablani</a></h4>\r\n");
      out.write("                                <p class=\"theme-color marB10\">Class Teacher</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Our Staff end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Feedback starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB50\">\r\n");
      out.write("            <!--- Theme heading start-->\r\n");
      out.write("            <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                            <h3 class=\"theme-color marB10\">Parents Feedback</h3>\r\n");
      out.write("                            <span class=\" marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            <p class=\" marB10\">\r\n");
      out.write("                            The Best Feeling a child can have is when there is someone \r\n");
      out.write("                            who can capture the smallest actions of him.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--- Theme heading end-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-8 col-sm-8 col-xs-12\">\r\n");
      out.write("                        <div class=\"theme-hover marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/1.jpg\" alt=\"\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                                <div class=\"theme-hover marB30\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/2.jpg\" alt=\"\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                                <div class=\"theme-hover marB30\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/3.jpg\" alt=\"\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Feedback end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Blog starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB50 bagG\">\r\n");
      out.write("            <!--- Theme heading start-->\r\n");
      out.write("            <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                            <h3 class=\"theme-color marB10\">Our Blog</h3>\r\n");
      out.write("                            <span class=\" marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            <p class=\" marB10\">The Best Feeling a child can have is when there is someone \r\n");
      out.write("                            who can capture the smallest actions of him.\r\n");
      out.write("                            \r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--- Theme heading end-->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"blog-img marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/aakash.jpg\" alt=\"\"/>\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-detail marB30\">\r\n");
      out.write("                            <h4 class=\"colorB marB10 title text-left\"><a href=\"blog-single-sidebar.html\">Blog on Child Safety</a></h4>\r\n");
      out.write("                            <p class=\"marB10 text-left\"> \r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-calendar marR5\" aria-hidden=\"true\"></i>May 24, 2015</span></a>\r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-comment marR5\" aria-hidden=\"true\"></i>12 Comments</span></a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"marB10 text-left\">The Best Feeling a child can have is when there is someone \r\n");
      out.write("                            who can capture the smallest actions of him.\r\n");
      out.write("                            \r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"marB10 text-left\"><a href=\"blog-single-sidebar.html\">Read more<i class=\"fa fa-angle-double-right marL10\" aria-hidden=\"true\"></i></a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"blog-img marB30\">\r\n");
      out.write("                            <div id=\"blog-slider\" class=\"owl-carousel owl-theme slider positionR marB30\">\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/aakash.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/reena.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"userResources/images/vrinda.jpg\" alt=\"\"/>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-detail marB30\">\r\n");
      out.write("                            <h4 class=\"colorB marB10 title text-left\"><a href=\"blog-single-sidebar.html\">Blog on Child Monitoring.</a></h4>\r\n");
      out.write("                            <p class=\"marB10 text-left\"> \r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-calendar marR5\" aria-hidden=\"true\"></i>May 24, 2015</span></a>\r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-comment marR5\" aria-hidden=\"true\"></i>12 Comments</span></a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"marB10 text-left\">The Best Feeling a child can have is when there is someone \r\n");
      out.write("                            who can capture the smallest actions of him.\r\n");
      out.write("                            \r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"marB10 text-left\"><a href=\"blog-single-sidebar.html\">Read more<i class=\"fa fa-angle-double-right marL10\" aria-hidden=\"true\"></i></a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"blog-img marB30\">\r\n");
      out.write("                            <figure>\r\n");
      out.write("                                <img src=\"userResources/images/vrinda.jpg\" alt=\"\"/>\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-detail marB30\">\r\n");
      out.write("                            <h4 class=\"colorB marB10 title text-left\"><a href=\"blog-single-sidebar.html\">Blog on Providing Help to Working parents</a></h4>\r\n");
      out.write("                            <p class=\"marB10 text-left\"> \r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-calendar marR5\" aria-hidden=\"true\"></i>May 24, 2015</span></a>\r\n");
      out.write("                                <a href=\"#\"><span class=\"marR10\"><i class=\"fa fa-comment marR5\" aria-hidden=\"true\"></i>12 Comments</span></a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"marB10 text-left\"> The Best Feeling a child can have is when there is someone\r\n");
      out.write("                                rinting andey typesetting industry.\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p><a href=\"blog-single-sidebar.html\" class=\"text-left\">Read more<i class=\"fa fa-angle-double-right marL10\" aria-hidden=\"true\"></i></a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Blog end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================partener starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB80\">\r\n");
      out.write("            <!--- Theme heading start-->\r\n");
      out.write("            <div class=\"theme-heading marB30 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-6 col-xs-10  col-md-offset-4 col-sm-offset-3 col-xs-offset-1 heading-box text-center\">\r\n");
      out.write("                            <h3 class=\"theme-color marB10\">Our Parteners</h3>\r\n");
      out.write("                            <span class=\" marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            <p class=\" marB10\">\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--- Theme heading end-->\r\n");
      out.write("            <div class=\"clear\"></div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div id=\"partener-slider\" class=\"owl-carousel partener-slides owl-theme owl-loaded owl-drag carousel-style-1\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/mimo.png\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/owlet.jpg\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/nanit.jpg\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/monbaby.png\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/mimo.png\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/owlet.jpg\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\">\r\n");
      out.write("                                    <img src=\"userResources/images/nanit.jpg\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <figure class=\"border-box\"> \r\n");
      out.write("                                    <img src=\"userResources/images/monbaby.png\" alt=\"\">\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!--//================contact us starts==============//-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chotaContact.jsp", out, false);
      out.write("\r\n");
      out.write("        <!--//================contact us end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write(" \t\r\n");
      out.write("        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("        <script src=\"userResources/js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/hover-dropdown-menu.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/jquery.hover-dropdown-menu-addon.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/jquery.fancybox-media.js\"></script> \r\n");
      out.write("        <script src=\"userResources/js/main.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
