/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2018-04-12 03:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewImage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/K:/Classes/Advance%20Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Baby_Monitoring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522667820988L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <!--[if IE]>\r\n");
      out.write("        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("        <meta name=\"keywords\" content=\"HTML5 Template\" />\r\n");
      out.write("        <meta name=\"description\" content=\"Baby House - Kids School, Kinder Garden & Play School Multipurpose HTML5 Template\" />\r\n");
      out.write("        <meta name=\"author\" content=\"itgeeksin.com\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("        <title>Baby House - Kids School, Kinder Garden & Play School </title>\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("        <!-- Favicon -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"userResources/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("        <link rel=\"icon\" href=\"userResources/images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("        <!-- Master Css -->\r\n");
      out.write("        <link href=\"userResources/css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--//================Header start==============//-->  \r\n");
      out.write("\t\t   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("           <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Breadcrumb starts==============//-->\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"bredcrumb-section padTB100 positionR\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div class=\"theme-heading text-center\">\r\n");
      out.write("                                <h3 class=\"text-center theme-color\">Image Upload</h3>\r\n");
      out.write("                                <span class=\"colorW marB10\"> <i class=\"fa fa-child\" aria-hidden=\"true\"></i> </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"breadcrumb-box\">\r\n");
      out.write("                                <ul class=\"breadcrumb text-center colorW marB0\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"index.html\">Home</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"active\">Image Upload</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Breadcrumb end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================Register starts==============//-->\r\n");
      out.write("        <section class=\"padT80 padB50\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-sm-8 col-xs-12 col-md-offset-3 col-sm-offset-2 col-xs-offset-0\">\r\n");
      out.write("                        <form action=\"http://127.0.0.1:5011/baby_cry_anger_happy\" method=\"get\">\r\n");
      out.write("\t\t\t                        <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t                            <h4 class=\"marB30 title\">Upload the Image for the detection of Expression of babies.</h4>\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("                        \t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn btn-raised \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												Integer s=(Integer) session.getAttribute("loginId");
												//out.println(s);
											
      out.write("\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"loginId\" name=\"loginId\"value= \"");
      out.print(s);
      out.write("\" style=\"display : none\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                        \t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-sm-3 control-label\">File </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn btn-raised \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tSelect File <input type=\"file\" class=\"btn btn-raised btn-default\" placeholder=\"File Name\" id=\"file\" name=\"file\" data-parsley-trigger=\"change\" required=\"required\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn btn-raised \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"anim\" src=\"userResources/images/8YsAmq3.gif\" style=\"display : none\"></img>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"boxs-footer text-right bg-tr-black lter dvd dvd-top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" onclick=\"fn()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--//================Register end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!--//================contact us starts==============//-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chotaContact.jsp", out, false);
      out.write("\r\n");
      out.write("        <!--//================contact us end==============//-->\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("        <script src=\"userResources/js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/hover-dropdown-menu.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/jquery.hover-dropdown-menu-addon.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("        <script src=\"userResources/js/main.js\"></script>\r\n");
      out.write("    \t<script type=\"text/javascript\">\r\n");
      out.write("        function fn(){\r\n");
      out.write("        \t\tvar image=document.getElementById(\"anim\");\r\n");
      out.write("        \t\timage.style.display = \"\"\r\n");
      out.write("        \t}\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("    \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
